apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: dev
  
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: acrecomm.azurecr.io/rabbitmq:3-management
        ports:
        - containerPort: 8082